### ISSUE TITLE
error on `sudo pip install -U jujulocal`

### ISSUE THREAD

**Issue by tyloch** [juju-solutions/juju-local#1]
I've got the following error:

```
~$ sudo pip install -U jujulocal
Downloading/unpacking jujulocal
  Could not find any downloads that satisfy the requirement jujulocal
Cleaning up...
No distributions at all found for jujulocal
Storing debug log for failure in /home/artur/.pip/pip.log
```

pip.log file: 

```
/usr/bin/pip run on Sun Jun 21 22:03:59 2015
Downloading/unpacking jujulocal
  Getting page https://pypi.python.org/simple/jujulocal/
  Could not fetch URL https://pypi.python.org/simple/jujulocal/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/jujulocal/ when looking for download links for jujulocal
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for jujulocal:
  * https://pypi.python.org/simple/jujulocal/
  Getting page https://pypi.python.org/simple/jujulocal/
  Could not fetch URL https://pypi.python.org/simple/jujulocal/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/jujulocal/ when looking for download links for jujulocal
  Could not find any downloads that satisfy the requirement jujulocal
Cleaning up...
No distributions at all found for jujulocal
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for jujulocal
```

**Comment by marcoceppi** [comment]
I've updated the README and registered the project on PyPI. Unfortunately, the project isn't complete yet and isn't actually released on PyPI. Instead, download the source code and make it in a local virtualenv to test and use.
